apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "default-pool"
spec:
  cidrs:
    - cidr: "10.46.1.0/24"
    - cidr: "2001:67c:1104:e04e::/64"

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "dna-pool"
spec:
  cidrs:
    - cidr: "10.46.2.0/24"
    - cidr: "2001:14ba:16fd:961d::e:0/112"
  serviceSelector:
    matchLabels:
      pool: dna
