apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: "linux"
  virtualRouters:  # []CiliumBGPVirtualRouter
    - localASN: 213021
      exportPodCIDR: true
      serviceSelector:
        matchExpressions:
          - {key: allservices, operator: NotIn, values: ['will-be-announced']}
      neighbors:   # []CiliumBGPNeighbor
        - peerAddress: "10.0.110.1/32"
          peerASN: 213021
        - peerAddress: "2001:14ba:16fd:961d::1/128"
          peerASN: 213021
